relativeURLs: true
title: "Laurits Fredsgaard Larsen"
theme: "academimal"
sectionPagesMenu: "main"
defaultContentLanguage: "en"

author:
  name: "Laurits Fredsgaard Larsen"
  homepage: "https://laurits.me/"

params:
  shortbio: "PhD student in Applied Mathematics and Computer Science at DTU"
  ORCID: "0000-0003-3891-3414"
  GitHub: "lauritsf"
  GoogleScholar: "HjUEfBUAAAAJ"
  LinkedIn: "lauritsfredsgaard"

markup:
  highlight:
    style: "solarized-dark"
  goldmark:
    renderer:
      unsafe: true
